### ISSUE TITLE
WSGIRequest object has no attribute _errormator_create_report

### ISSUE THREAD

**Issue by davidfischer-ch** [AppEnlight/appenlight-client-python#26]
appenlight_client/django_middleware.py in process_response, line 86
Issued when simulating concurrent requests using locust.io to load-test my infrastructure.

**Comment by ergo** [comment]
Hi David,

Are you sure that our middleware is the FIRST in your django middleware stack?

This is the most common case when this happens for django applications.

**Comment by davidfischer-ch** [comment]
Hi,

I will test it tomorrow.

Thanks.

**Comment by davidfischer-ch** [comment]
Hi,
Indeed putting the middleware as the really first fixed this issue!
Thanks.
