### ISSUE TITLE
'template' key in jinja2 renderer breaks the client

### ISSUE THREAD

**Issue by jpfarias** [AppEnlight/appenlight-client-python#27]
We run into an issue where having a 'template' key in the jinja2 context data dictionary breaks when using appenlight in pyramid.

Looks like appenlight decorator tries to do an updade on the dictionary with that key duplicated on such case.

I renamed the data key to something else and it worked.

**Comment by ergo** [comment]
Can you please provide me with an exception that illustrates this?
It will help me to recreate the issue.

**Comment by jpfarias** [comment]
```
(Pdb) kwargs.keys()
['property', 'template', 'substandard_items', 'loan', 'request', 'escrow', 'lender', 'escrow_holder', 'selected_templates', 'borrower', 'prelims', 'title_company', 'document']
(Pdb) n
TypeError: "gather_template() got multiple values for keyword argument 'template'"
> /home/anchor/env/local/lib/python2.7/site-packages/appenlight_client-0.6.12-py2.7.egg/appenlight_client/timing/__init__.py(114)wrapper()
-> info.update(gatherer(*args, **kwargs))
```

**Comment by ergo** [comment]
Can you please open the file:
/appenlight_client/timing/timing_jinja2.py
and rename the template argument to something like _ae_template and in the line below and see if this helps?
When I'm home I can test this myself later, but this would speed up the fix :-)

Thanks

**Comment by jpfarias** [comment]
We are not in a rush, we renamed our own key and it worked. Let me know if you fix it though. Thanks for the quick response.

**Comment by jpfarias** [comment]
Did you have a chance to look into this?

Thanks again,

--
JP

**Comment by ergo** [comment]
Yes, can you test if the trunk client with latest commit fixes the issue for you completly?
