### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute '__start_time__'

### ISSUE THREAD

**Issue by luk156** [AppEnlight/appenlight-client-python#29]
File "/home/django/.virtualenvs/get3-dev/lib/python2.7/site-packages/appenlight_client/django_middleware.py", line 95, in process_response
    delta = timedelta(seconds=(end_time - request.**start_time**))
AttributeError: 'WSGIRequest' object has no attribute '**start_time**'

**Comment by ergo** [comment]
Hi @luk156,

Did you alter the django middleware in any way?
line 95 of the django middleware says:

    delta = timedelta(seconds=(end_time - request.__start_time__))

Also is appenlight django middleware the FIRST middleware that is registered in django stack as docs advise? Usually errors related to missing attribute happen only if the middleware is further down the stack and something above it triggers an exception.
