### ISSUE TITLE
setup.py should not import anything

### ISSUE THREAD

**Issue by kbrownlees** [AppEnlight/appenlight-client-python#35]
If you try and install into a fresh virtualenv it will fail because the pass of setup.py required to find the requirements imports appenlight_client which imports the actual client and generates an ImportError.

```
Collecting appenlight-client==0.6.18 (from -r /app/requirements.txt (line 26))
  Downloading appenlight_client-0.6.18.tar.gz (46kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_jxiewns/appenlight-client/setup.py", line 1, in <module>
        import appenlight_client
      File "/tmp/pip-build-_jxiewns/appenlight-client/appenlight_client/__init__.py", line 18, in <module>
        from appenlight_client.client import make_appenlight_middleware
      File "/tmp/pip-build-_jxiewns/appenlight-client/appenlight_client/client.py", line 42, in <module>
        from webob import Request
    ImportError: No module named 'webob'
```

**Comment by ergo** [comment]
Thank you, I'm very sorry this problem slipped by. It is fixed in latest release on pypi.

**Comment by kbrownlees** [comment]
Thank you for the quick fix!

Not sure if you know about it or not but bumpversion (https://github.com/peritus/bumpversion) is a great tool for keeping versions in sync across multiple files.

**Comment by ergo** [comment]
Yes, I know about it - will implement it in future (soon).
