### ISSUE TITLE
Allow Blacklisting of environ_keys

### ISSUE THREAD

**Issue by corvuscrypto** [AppEnlight/appenlight-client-python#42]
Currently only whitelisting environ variables is allowed. However, I cannot blacklist, for instance, HTTP_COOKIE without modifying the library locally. This is important for me (and perhaps others) because I am not okay with allowing signed tokens to be seen by staff reviewing these logs. I can make a PR soon probably for this, but this would be extremely helpful.

**Comment by ergo** [comment]
Hi,

You can do this by providing custom `appenlight.filter_callable`.

https://github.com/AppEnlight/appenlight-client-python/blob/master/appenlight_client/client.py#L279

Here is the reference implementation, I think if you use `request_keys_blacklist` and you know the token cookie name you should be able to filter them out.

**Comment by corvuscrypto** [comment]
MMMMMMMMMmmmmm you're right. missed this. Thanks I can indeed implement what I need using a custom filter_callable. Thanks! Closing this

**Comment by ergo** [comment]
Np.

Feel free to reopen if you have trouble getting it to work.

Cheers!
