### ISSUE TITLE
django

### ISSUE THREAD

**Issue by xazrad** [AppEnlight/appenlight-client-python#47]
I added middleware 'django.middleware.security.SecurityMiddleware', I also have my custom middleware. When execute request.user.is_authenticated() in custom middleware exeption  appears AttributeError ```__exit__```

**Comment by ergo** [comment]
Can you post whole exception here and describe your problem in more detail?
Do you think you have issues created by AE middleware?

**Comment by ergo** [comment]
Hey @xazrad It has been a while, I got another similar error and I think your problem was related to lack of support for context managers. Can you try trunk version of AE client to see if this is now fixed for you?
