### ISSUE TITLE
'AsgiRequest' object has no attribute 'environ'

### ISSUE THREAD

**Issue by luk156** [AppEnlight/appenlight-client-python#52]
with daphne https://github.com/django/daphne i've this error:
'AsgiRequest' object has no attribute 'environ'

**Comment by ergo** [comment]
Hi, sounds like ASGI does not have same keys as WSGI interfaces, is there a chance you can prepare some minimal hello world reproduction for me that exposes this error?

**Comment by luk156** [comment]
I'll try this week

**Comment by luk156** [comment]
it seems work

![schermata da 2018-06-05 22-31-30](https://user-images.githubusercontent.com/1016684/41001100-44587198-6910-11e8-9f34-afb11e78832b.png)

**Comment by ergo** [comment]
I think this is now fixed. So closing.
